### ISSUE TITLE
question on permissions used

### ISSUE THREAD

**Issue by IzzySoft** [broscr/IPTV-Player#19]
My scanner got some additional checks implemented last week, and today, receiving your first update since, reported:

```
! repo/com.broscr.iptvplayer_4.apk declares flag(s): usesCleartextTraffic
! repo/com.broscr.iptvplayer_4.apk declares risky permission(s): android.permission.READ_EXTERNAL_STORAGE android.permission.READ_MEDIA_AUDIO
```

Could you please clarify those?

* `usesCleartextTraffic`: are there any stations out there still using unencrypted HTTP?
* `READ_EXTERNAL_STORAGE`: the minimum Android version needed to use your app is Android 5, which introduced SAF (Storage Access Framework). Is this permission still needed then?
* `READ_MEDIA_AUDIO`: any locally hosted TV stations there? :see_no_evil:

Thanks in advance!

**Comment by broscr** [comment]
- usesCleartextTraffic: are there any stations out there still using unencrypted HTTP?
Yes, there may be stations that use it, I have no definitive information about it, I added it because I saw http requests while testing.

- READ_EXTERNAL_STORAGE: the minimum Android version needed to use your app is Android 5, which introduced SAF (Storage Access Framework). Is this permission still needed then?
Up to Android version 32, it is possible to read files with this permission. The user gets this permission to choose among all his files.

- READ_MEDIA_AUDIO: any locally hosted TV stations there? 
Note: Starting in API level 33, this permission has no effect. If your app accesses other apps' media files, request one or more of these permissions instead: [READ_MEDIA_IMAGES](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_IMAGES), [READ_MEDIA_VIDEO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_VIDEO), [READ_MEDIA_AUDIO](https://developer.android.com/reference/android/Manifest.permission#READ_MEDIA_AUDIO). Learn more about the [storage permissions](https://developer.android.com/training/data-storage/shared/media#storage-permission) that are associated with media files.
[READ_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE)

**Comment by IzzySoft** [comment]
* usesCleartextTraffic: Thought so, thanks for confirming! Added to the allow-list of your app (so it no longer gets reported with future updates).
* READ_EXTERNAL_STORAGE: I just learned this is still needed up to Android 9 if you want to access other apps' media files (for later Android versions one should use `READ_MEDIA_AUDIO`  etc; updating my notes here I noticed I've seen that earlier but it somehow escaped my memory, apologies for that). So I assume you refer to those? Then this point can be skipped and "merged" with the next one:
* READ_MEDIA_AUDIO: yes, see above. But according to the app description (or according to how it can be read) and the app's name, it's intended for IPTV. Does it allow to play local media, too – and are you referring to local M3U playlists for local media then?

**Comment by broscr** [comment]
- READ_MEDIA_AUDIO: yes, see above. But according to the app description (or according to how it can be read) and the app's name, it's intended for IPTV. Does it allow to play local media, too – and are you referring to local M3U playlists for local media then?.
In fact, this application is a player and all it does is to let the user select m3u and m3u8 files, read their content, save it in localdb and play it as a list.

**Comment by IzzySoft** [comment]
```yaml
    FlagIgnore:
      usesCleartextTraffic: Needed for some TV stations which only provide their streams over unencrypted HTTP.
    PermIgnore:
      android.permission.READ_EXTERNAL_STORAGE: Needed to access media saved/stored by other apps.
      android.permission.READ_MEDIA_AUDIO: Needed to play your local audio files.
```

Thanks!
